Create code-review-dance-activity.md
hmc-cs121-admin/git-pm-workflow pull request #2
Opened 2018-02-21 02:11 UTC by blakeLarkin

This is my new version of the code review activity, based on the existing Github Tutorial.

2018-03-02 04:02 UTC, blakeLarkin commented
Need to explain how to make a PR and make it explicit to use the repo from the other exercise

2018-03-02 04:14 UTC, blakeLarkin commented on code-review-dance-activity.md
> +  Go to the project's "Settings" tab and from the left sidebar select "Branches". Under the "Protected Branches" select the master branch to protect it from deletion and pushes. Require changes to ma
Clarify what is meant by "project's 'Settings'"

2018-03-02 04:22 UTC, blakeLarkin commented on code-review-dance-activity.md
> +  PR by including “@[Developer A’s github handle]” in the description
This is where I may need to describe making PRs

2018-03-02 04:23 UTC, blakeLarkin commented on code-review-dance-activity.md
> +  Now comment on the problems in the code, including:
Say how to leave comments

2018-03-02 04:24 UTC, blakeLarkin commented on code-review-dance-activity.md
> +  Now comment on the problems in the code, including:
explain difference between single comments and a review

2018-03-02 04:24 UTC, blakeLarkin commented on code-review-dance-activity.md
> +  Now comment on the problems in the code, including:
and if doing a review make sure that you don't approve it if there are issues

2018-03-02 04:25 UTC, blakeLarkin commented on code-review-dance-activity.md
> +  Now comment on the problems in the code, including:
Infact, select "Request Changes"

2018-03-02 04:27 UTC, blakeLarkin commented on code-review-dance-activity.md
> +  Git add and push your changes and verify that your changes have been updated on the PR.
leave good commit messages

2018-03-02 04:29 UTC, blakeLarkin commented on code-review-dance-activity.md
> +
Talk about deleting branches

2018-03-02 05:50 UTC, ykharitonova requested changes
Looks like my comments are currently "pending"; let's see if "request changes" puts them through...

2018-03-02 05:50 UTC, ykharitonova commented on code-review-dance-activity.md
> +- You have a basic repository, akin to the one created in the other tutorial, with mandatory code reviews
what does it mean: "with mandatory code reviews"?

2018-03-02 05:50 UTC, ykharitonova commented on code-review-dance-activity.md
> +-   Developer A: Set's up required reviews and reviews Developer B's pull request (PR)
Set's up --> Sets up

2018-03-02 05:50 UTC, ykharitonova commented on code-review-dance-activity.md
> +-   Developer B: Create's an erroneous addition and attempts to create a pull request
no need for an apostrophe

2018-03-02 05:50 UTC, ykharitonova commented on code-review-dance-activity.md
> +Performing these code reviews (4) foster learning from your development team and sharing your own expertise.
fosters

2018-03-02 05:50 UTC, ykharitonova commented on code-review-dance-activity.md
> +- You have a basic repository, akin to the one created in the other tutorial, with mandatory code reviews
Is it what you explained in Step 1? If they do it there, then it's not a prereq?

2018-03-02 05:50 UTC, ykharitonova commented on code-review-dance-activity.md
> +  * Finally, inside the inner for loop print “Hi” with “puts “Hi””
use code marks, i.e. `backticks`, for code-related lines

2018-03-02 05:50 UTC, ykharitonova commented on code-review-dance-activity.md
> +  Navigate to the "Pull Requests" tab and open the new PR. Click on the “Files Changed” tab to see what the pull request covers.
the "Pull Requests" tab on GitHub

2018-03-02 05:50 UTC, ykharitonova commented on code-review-dance-activity.md
> +  Check your pull request on Github and read over the comments Developer A has
Check your "Pull Requests" tab on GitHub

2018-03-02 05:50 UTC, ykharitonova commented on code-review-dance-activity.md
> +  Refresh your pull request. Since Developer A has approved it, the merge button should now be clickable. Merge it!
Isn't this dependent on the configuration of the repo? I.e., is it enough to just be the collaborator on the repo to merge the commit in?

2018-03-05 22:21 UTC, blakeLarkin commented on code-review-dance-activity.md
> +  Refresh your pull request. Since Developer A has approved it, the merge button should now be clickable. Merge it!
Yes, I changed the instructions earlier to allow collaborators to approve PRs (not only owners). I believe if they are in the same groups as the first assignment it should work.

2018-03-05 22:24 UTC, blakeLarkin commented on code-review-dance-activity.md
> +
I added this

2018-03-07 04:14 UTC, ykharitonova approved these changes

2018-03-07 04:19 UTC, azwildcat approved these changes
Let's merge this activity into the main repo.

2018-03-07 04:40 UTC, azwildcat approved these changes

2018-03-07 04:40 UTC, merged